Message receipt documentation for startChatContactAPI example
amazon-connect/amazon-connect-chat-ui-examples pull request #81
Opened 2022-11-28 17:25 UTC by spencerlepine

*Issue #, if available:*
Documentation for new message receipts feature

*Description of changes:*
Added documentation for enabling message receipts feature for out-of-the-box chat-interface solution. Also added a link to steps for enabling message receipts through Admin UI.

- Gave updates for the correct ChatJS configuration options to enable sending read/delivered events to the backend.
- Gave updates the the UI (component props) to pass down `shouldShowMessageReceipts` to children, which will render the read/delivered status.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-27 18:57 UTC, mhiaror requested changes

2022-12-27 18:57 UTC, mhiaror commented on cloudformationTemplates/asyncCustomerChatUX/README.md
> +
`Ensure that the ChatJs feature configuration is set as well:` - best to add this to the section for `disabling message-receipts`

Also, you can explain about throttling in a separate section.

2022-12-27 18:57 UTC, mhiaror commented on cloudformationTemplates/startChatContactAPI/README.md
> +Ensure that the ChatJs feature configuration is set as well:
same comment as above; this should be part of `disabling` not `enabling` section.

2022-12-28 20:52 UTC, mhiaror approved these changes

2022-12-28 20:54 UTC, jiahaoyu6666 submitted a review, later dismissed

2022-12-28 21:08 UTC, merged